<?php

declare(strict_types=1);

/**
 * @var array{
 *     initial: array-key,
 *     tokens: array{
 *         default: array<non-empty-string, non-empty-string>,
 *         ...
 *     },
 *     skip: list<non-empty-string>,
 *     grammar: array<array-key, \Phplrt\Parser\Grammar\RuleInterface>,
 *     reducers: array<array-key, callable(\Phplrt\Parser\Context, mixed):mixed>,
 *     transitions?: array<array-key, mixed>
 * }
 */
return [
    'initial' => 'Document',
    'tokens' => [
        'default' => [
            'T_WHITESPACE' => '[\\x20\\t]+',
            'T_HELP' => 'HELP',
            'T_TYPE' => 'TYPE',
            'T_UNIT' => 'UNIT',
            'T_EOF' => 'EOF',
            'T_COMMENT' => '^\\#(?![\\x20\\t]+(?:HELP|TYPE|UNIT|EOF))[\\x20\\t]+([^\\n\\\\]|\\\\[n"\\\\])+$',
            'T_FLOAT' => '[+-]?[0-9]*\\.[0-9]+([eE][+-]?[0-9]+)?|[+-]?[0-9]+[eE][+-]?[0-9]+',
            'T_INF' => '[+-](?i)inf(inity)?',
            'T_INT' => '[+-]?[0-9]+',
            'T_NAN' => '(?i)nan',
            'T_EQUAL' => '\\=',
            'T_HASH' => '\\#',
            'T_LBRACE' => '{',
            'T_RBRACE' => '}',
            'T_COMMA' => '\\,',
            'T_EOR' => '\\r',
            'T_EOL' => '\\n',
            'T_START_TIMESTAMP' => 'st@',
            'T_METRIC_TYPE' => '(summary|counter|gaugehistogram|gauge|histogram|stateset|info|unknown|untyped)',
            'T_METRIC_NAME' => '[a-zA-Z_:][a-zA-Z0-9_:]*',
            'T_QUOTED_STRING' => '\\"([^\\n"\\\\]|\\\\[n"\\\\])+\\"',
            'T_TEXT' => '([^\\n\\\\]|\\\\[n"\\\\])+',
        ],
    ],
    'skip' => [],
    'transitions' => [],
    'grammar' => [
        0 => new \Phplrt\Parser\Grammar\Repetition('MetricData', 0, INF),
        1 => new \Phplrt\Parser\Grammar\Optional('Eof'),
        2 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        3 => new \Phplrt\Parser\Grammar\Concatenation(['Help', 'Type', 2]),
        4 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        5 => new \Phplrt\Parser\Grammar\Optional('Type'),
        6 => new \Phplrt\Parser\Grammar\Concatenation(['Help', 4, 5]),
        7 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        8 => new \Phplrt\Parser\Grammar\Concatenation(['Type', 'Help', 7]),
        9 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        10 => new \Phplrt\Parser\Grammar\Optional('Help'),
        11 => new \Phplrt\Parser\Grammar\Concatenation(['Type', 9, 10]),
        12 => new \Phplrt\Parser\Grammar\Optional('Help'),
        13 => new \Phplrt\Parser\Grammar\Concatenation(['Unit', 'Type', 12]),
        14 => new \Phplrt\Parser\Grammar\Optional('Help'),
        15 => new \Phplrt\Parser\Grammar\Optional('Type'),
        16 => new \Phplrt\Parser\Grammar\Concatenation(['Unit', 14, 15]),
        17 => new \Phplrt\Parser\Grammar\Repetition('Comment', 0, INF),
        18 => new \Phplrt\Parser\Grammar\Alternation([3, 6, 8, 11, 13, 16]),
        19 => new \Phplrt\Parser\Grammar\Repetition('Metric', 0, INF),
        20 => new \Phplrt\Parser\Grammar\Concatenation([17, 18, 19]),
        21 => new \Phplrt\Parser\Grammar\Repetition('Comment', 0, INF),
        22 => new \Phplrt\Parser\Grammar\Repetition('Metric', 1, INF),
        23 => new \Phplrt\Parser\Grammar\Concatenation([21, 22]),
        24 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        25 => new \Phplrt\Parser\Grammar\Repetition(138, 1, INF),
        26 => new \Phplrt\Parser\Grammar\Repetition(24, 0, INF),
        27 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMENT', true),
        28 => new \Phplrt\Parser\Grammar\Optional(25),
        29 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        30 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_NAME', true),
        31 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        32 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        33 => new \Phplrt\Parser\Grammar\Concatenation([32, 'HelpDocstring']),
        34 => new \Phplrt\Parser\Grammar\Repetition(29, 0, INF),
        35 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        36 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        37 => new \Phplrt\Parser\Grammar\Lexeme('T_HELP', false),
        38 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        39 => new \Phplrt\Parser\Grammar\Alternation([30, 31]),
        40 => new \Phplrt\Parser\Grammar\Optional(33),
        41 => new \Phplrt\Parser\Grammar\Optional(25),
        42 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_NAME', true),
        43 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_TYPE', true),
        44 => new \Phplrt\Parser\Grammar\Lexeme('T_EQUAL', true),
        45 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', true),
        46 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', true),
        47 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', true),
        48 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        49 => new \Phplrt\Parser\Grammar\Lexeme('T_START_TIMESTAMP', true),
        50 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        51 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', true),
        52 => new \Phplrt\Parser\Grammar\Alternation([42, 43, 'MetricValue', 44, 45, 46, 47, 48, 49, 50]),
        53 => new \Phplrt\Parser\Grammar\Repetition(51, 0, INF),
        54 => new \Phplrt\Parser\Grammar\Concatenation([52, 53]),
        55 => new \Phplrt\Parser\Grammar\Lexeme('T_TEXT', true),
        56 => new \Phplrt\Parser\Grammar\Repetition(54, 0, INF),
        57 => new \Phplrt\Parser\Grammar\Optional(55),
        58 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        59 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_NAME', true),
        60 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        61 => new \Phplrt\Parser\Grammar\Repetition(58, 0, INF),
        62 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        63 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        64 => new \Phplrt\Parser\Grammar\Lexeme('T_TYPE', false),
        65 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        66 => new \Phplrt\Parser\Grammar\Alternation([59, 60]),
        67 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        68 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_TYPE', true),
        69 => new \Phplrt\Parser\Grammar\Optional(25),
        70 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        71 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_NAME', true),
        72 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        73 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        74 => new \Phplrt\Parser\Grammar\Concatenation([73, 'UnitUnit']),
        75 => new \Phplrt\Parser\Grammar\Repetition(70, 0, INF),
        76 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        77 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        78 => new \Phplrt\Parser\Grammar\Lexeme('T_UNIT', false),
        79 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        80 => new \Phplrt\Parser\Grammar\Alternation([71, 72]),
        81 => new \Phplrt\Parser\Grammar\Optional(74),
        82 => new \Phplrt\Parser\Grammar\Optional(25),
        83 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        84 => new \Phplrt\Parser\Grammar\Repetition(83, 0, INF),
        85 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        86 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        87 => new \Phplrt\Parser\Grammar\Lexeme('T_EOF', false),
        88 => new \Phplrt\Parser\Grammar\Optional(25),
        89 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        90 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        91 => new \Phplrt\Parser\Grammar\Concatenation([90, 'MetricTimestamp']),
        92 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        93 => new \Phplrt\Parser\Grammar\Concatenation([92, 'MetricStartTimestamp']),
        94 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        95 => new \Phplrt\Parser\Grammar\Concatenation([94, 'Exemplar']),
        96 => new \Phplrt\Parser\Grammar\Repetition('Comment', 0, INF),
        97 => new \Phplrt\Parser\Grammar\Repetition(89, 0, INF),
        98 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_NAME', true),
        99 => new \Phplrt\Parser\Grammar\Optional('Labels'),
        100 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        101 => new \Phplrt\Parser\Grammar\Optional(91),
        102 => new \Phplrt\Parser\Grammar\Optional(93),
        103 => new \Phplrt\Parser\Grammar\Optional(95),
        104 => new \Phplrt\Parser\Grammar\Optional(25),
        105 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        106 => new \Phplrt\Parser\Grammar\Concatenation([105, 'MetricTimestamp']),
        107 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        108 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        109 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        110 => new \Phplrt\Parser\Grammar\Optional(106),
        111 => new \Phplrt\Parser\Grammar\Lexeme('T_FLOAT', true),
        112 => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        113 => new \Phplrt\Parser\Grammar\Lexeme('T_INF', true),
        114 => new \Phplrt\Parser\Grammar\Lexeme('T_NAN', true),
        115 => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        116 => new \Phplrt\Parser\Grammar\Lexeme('T_FLOAT', true),
        117 => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        118 => new \Phplrt\Parser\Grammar\Lexeme('T_FLOAT', true),
        119 => new \Phplrt\Parser\Grammar\Lexeme('T_START_TIMESTAMP', false),
        120 => new \Phplrt\Parser\Grammar\Alternation([117, 118]),
        121 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        122 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', false),
        123 => new \Phplrt\Parser\Grammar\Repetition(121, 0, INF),
        124 => new \Phplrt\Parser\Grammar\Concatenation([122, 123]),
        125 => new \Phplrt\Parser\Grammar\Optional(124),
        126 => new \Phplrt\Parser\Grammar\Concatenation(['Label', 125]),
        127 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', false),
        128 => new \Phplrt\Parser\Grammar\Repetition(126, 0, INF),
        129 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', false),
        130 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_NAME', true),
        131 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        132 => new \Phplrt\Parser\Grammar\Alternation([130, 131]),
        133 => new \Phplrt\Parser\Grammar\Lexeme('T_EQUAL', false),
        134 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        135 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        136 => new \Phplrt\Parser\Grammar\Repetition(135, 0, INF),
        137 => new \Phplrt\Parser\Grammar\Lexeme('T_EOL', false),
        138 => new \Phplrt\Parser\Grammar\Concatenation([136, 137]),
        'Comment' => new \Phplrt\Parser\Grammar\Concatenation([26, 27, 28]),
        'Document' => new \Phplrt\Parser\Grammar\Concatenation(['Schema']),
        'Eof' => new \Phplrt\Parser\Grammar\Concatenation([84, 85, 86, 87, 88]),
        'Exemplar' => new \Phplrt\Parser\Grammar\Concatenation([107, 108, 'Labels', 109, 'MetricValue', 110]),
        'Help' => new \Phplrt\Parser\Grammar\Concatenation([34, 35, 36, 37, 38, 39, 40, 41]),
        'HelpDocstring' => new \Phplrt\Parser\Grammar\Concatenation([56, 57]),
        'Label' => new \Phplrt\Parser\Grammar\Concatenation([132, 133, 134]),
        'Labels' => new \Phplrt\Parser\Grammar\Concatenation([127, 128, 129]),
        'Metric' => new \Phplrt\Parser\Grammar\Concatenation([96, 97, 98, 99, 100, 'MetricValue', 101, 102, 103, 104]),
        'MetricData' => new \Phplrt\Parser\Grammar\Alternation([20, 23]),
        'MetricStartTimestamp' => new \Phplrt\Parser\Grammar\Concatenation([119, 120]),
        'MetricTimestamp' => new \Phplrt\Parser\Grammar\Alternation([115, 116]),
        'MetricValue' => new \Phplrt\Parser\Grammar\Alternation([111, 112, 113, 114]),
        'Schema' => new \Phplrt\Parser\Grammar\Concatenation([0, 1]),
        'Type' => new \Phplrt\Parser\Grammar\Concatenation([61, 62, 63, 64, 65, 66, 67, 68, 69]),
        'Unit' => new \Phplrt\Parser\Grammar\Concatenation([75, 76, 77, 78, 79, 80, 81, 82]),
        'UnitUnit' => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_NAME', true),
    ],
    'reducers' => [
        'Comment' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\CommentNode($children);
        },
        'Eof' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\EofNode($children);
        },
        'Exemplar' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\ExemplarNode($children);
        },
        'Help' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\HelpNode($children);
        },
        'HelpDocstring' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\HelpDocstringNode($children);
        },
        'Label' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\LabelNode($children);
        },
        'Labels' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\LabelsNode($children);
        },
        'Metric' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricNode($children);
        },
        'MetricData' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricDataNode($children);
        },
        'MetricStartTimestamp' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricStartTimestampNode($children);
        },
        'MetricTimestamp' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricTimestampNode($children);
        },
        'MetricValue' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricValueNode($children);
        },
        'Schema' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\SchemaNode($children);
        },
        'Type' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\TypeNode($children);
        },
        'Unit' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\UnitNode($children);
        },
        'UnitUnit' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\UnitUnitNode($children);
        },
    ],
];