<?php

declare(strict_types=1);

/**
 * @var array{
 *     initial: array-key,
 *     tokens: array{
 *         default: array<non-empty-string, non-empty-string>,
 *         ...
 *     },
 *     skip: list<non-empty-string>,
 *     grammar: array<array-key, \Phplrt\Parser\Grammar\RuleInterface>,
 *     reducers: array<array-key, callable(\Phplrt\Parser\Context, mixed):mixed>,
 *     transitions?: array<array-key, mixed>
 * }
 */
return [
    'initial' => 'Document',
    'tokens' => [
        'default' => [
            'T_WHITESPACE' => '[\\x20\\t]+',
            'T_HELP' => '\\bHELP\\b',
            'T_TYPE' => '\\bTYPE\\b',
            'T_UNIT' => '\\bUNIT\\b',
            'T_EOF' => '\\bEOF\\b',
            'T_COMMENT' => '^\\#(?![\\x20\\t]+(?:HELP|TYPE|UNIT|EOF))[\\x20\\t]+([^\\n\\\\]|\\\\[n"\\\\])+$',
            'T_FLOAT' => '[+-]?[0-9]*\\.[0-9]+([eE][+-]?[0-9]+)?|[+-]?[0-9]+[eE][+-]?[0-9]+\\b',
            'T_INF' => '[+-]?(?i)inf(inity)?\\b',
            'T_INT' => '[+-]?[0-9]+',
            'T_NAN' => '\\b(?i)nan\\b(?!:)',
            'T_EQUAL' => '=',
            'T_COLON' => '(?<=[a-zA-Z0-9_]):',
            'T_HASH' => '#',
            'T_LBRACE' => '{',
            'T_RBRACE' => '}',
            'T_LBRACKET' => '\\[',
            'T_RBRACKET' => '\\]',
            'T_COMMA' => ',',
            'T_EOR' => '\\r',
            'T_EOL' => '\\n',
            'T_START_TIMESTAMP' => '\\bst@',
            'T_METRIC_TYPE' => '\\b(summary|counter|gaugehistogram|gauge|histogram|stateset|info|unknown|untyped)\\b(?!:)',
            'T_COUNT' => '(?<=[{,])\\bcount\\b',
            'T_GCOUNT' => '(?<=[{,])\\bgcount\\b',
            'T_SUM' => '(?<=[{,])\\bsum\\b',
            'T_GSUM' => '(?<=[{,])\\bgsum\\b',
            'T_QUANTILE' => '(?<=[{,])\\bquantile\\b',
            'T_SCHEMA' => '(?<=[{,])\\bschema\\b',
            'T_ZERO_THRESHOLD' => '(?<=[{,])\\bzero_threshold\\b',
            'T_ZERO_COUNT' => '(?<=[{,])\\bzero_count\\b',
            'T_NEGATIVE_SPANS' => '(?<=[{,])\\bnegative_spans\\b',
            'T_NEGATIVE_BUCKETS' => '(?<=[{,])\\bnegative_buckets\\b',
            'T_POSITIVE_SPANS' => '(?<=[{,])\\bpositive_spans\\b',
            'T_POSITIVE_BUCKETS' => '(?<=[{,])\\bpositive_buckets\\b',
            'T_BUCKET' => '(?<=[{,])\\bbucket\\b',
            'T_METRIC_NAME' => '[a-zA-Z_:][a-zA-Z0-9_:]*',
            'T_QUOTED_STRING' => '\\"([^\\n"\\\\]|\\\\[n"\\\\])*\\"',
            'T_TEXT' => '([^\\n\\\\]|\\\\[n"\\\\])+',
        ],
    ],
    'skip' => [],
    'transitions' => [],
    'grammar' => [
        0 => new \Phplrt\Parser\Grammar\Repetition('MetricData', 0, INF),
        1 => new \Phplrt\Parser\Grammar\Optional('Eof'),
        2 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        3 => new \Phplrt\Parser\Grammar\Concatenation(['Help', 'Type', 2]),
        4 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        5 => new \Phplrt\Parser\Grammar\Optional('Type'),
        6 => new \Phplrt\Parser\Grammar\Concatenation(['Help', 4, 5]),
        7 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        8 => new \Phplrt\Parser\Grammar\Concatenation(['Type', 'Help', 7]),
        9 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        10 => new \Phplrt\Parser\Grammar\Optional('Help'),
        11 => new \Phplrt\Parser\Grammar\Concatenation(['Type', 9, 10]),
        12 => new \Phplrt\Parser\Grammar\Optional('Help'),
        13 => new \Phplrt\Parser\Grammar\Concatenation(['Unit', 'Type', 12]),
        14 => new \Phplrt\Parser\Grammar\Optional('Help'),
        15 => new \Phplrt\Parser\Grammar\Optional('Type'),
        16 => new \Phplrt\Parser\Grammar\Concatenation(['Unit', 14, 15]),
        17 => new \Phplrt\Parser\Grammar\Repetition('Comment', 0, INF),
        18 => new \Phplrt\Parser\Grammar\Alternation([3, 6, 8, 11, 13, 16]),
        19 => new \Phplrt\Parser\Grammar\Repetition('Metric', 0, INF),
        20 => new \Phplrt\Parser\Grammar\Concatenation([17, 18, 19]),
        21 => new \Phplrt\Parser\Grammar\Repetition('Comment', 0, INF),
        22 => new \Phplrt\Parser\Grammar\Repetition('Metric', 1, INF),
        23 => new \Phplrt\Parser\Grammar\Concatenation([21, 22]),
        24 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_NAME', true),
        25 => new \Phplrt\Parser\Grammar\Lexeme('T_NAN', true),
        26 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_TYPE', true),
        27 => new \Phplrt\Parser\Grammar\Lexeme('T_COUNT', true),
        28 => new \Phplrt\Parser\Grammar\Lexeme('T_GCOUNT', true),
        29 => new \Phplrt\Parser\Grammar\Lexeme('T_SUM', true),
        30 => new \Phplrt\Parser\Grammar\Lexeme('T_GSUM', true),
        31 => new \Phplrt\Parser\Grammar\Lexeme('T_QUANTILE', true),
        32 => new \Phplrt\Parser\Grammar\Lexeme('T_SCHEMA', true),
        33 => new \Phplrt\Parser\Grammar\Lexeme('T_ZERO_THRESHOLD', true),
        34 => new \Phplrt\Parser\Grammar\Lexeme('T_ZERO_COUNT', true),
        35 => new \Phplrt\Parser\Grammar\Lexeme('T_NEGATIVE_SPANS', true),
        36 => new \Phplrt\Parser\Grammar\Lexeme('T_NEGATIVE_BUCKETS', true),
        37 => new \Phplrt\Parser\Grammar\Lexeme('T_POSITIVE_SPANS', true),
        38 => new \Phplrt\Parser\Grammar\Lexeme('T_POSITIVE_BUCKETS', true),
        39 => new \Phplrt\Parser\Grammar\Lexeme('T_BUCKET', true),
        40 => new \Phplrt\Parser\Grammar\Alternation([24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),
        41 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        42 => new \Phplrt\Parser\Grammar\Repetition(275, 1, INF),
        43 => new \Phplrt\Parser\Grammar\Repetition(41, 0, INF),
        44 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMENT', true),
        45 => new \Phplrt\Parser\Grammar\Optional(42),
        46 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        47 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        48 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        49 => new \Phplrt\Parser\Grammar\Concatenation([48, 'HelpDocstring']),
        50 => new \Phplrt\Parser\Grammar\Repetition(46, 0, INF),
        51 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        52 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        53 => new \Phplrt\Parser\Grammar\Lexeme('T_HELP', false),
        54 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        55 => new \Phplrt\Parser\Grammar\Alternation([40, 47]),
        56 => new \Phplrt\Parser\Grammar\Optional(49),
        57 => new \Phplrt\Parser\Grammar\Optional(42),
        58 => new \Phplrt\Parser\Grammar\Lexeme('T_HELP', true),
        59 => new \Phplrt\Parser\Grammar\Lexeme('T_TYPE', true),
        60 => new \Phplrt\Parser\Grammar\Lexeme('T_UNIT', true),
        61 => new \Phplrt\Parser\Grammar\Lexeme('T_EOF', true),
        62 => new \Phplrt\Parser\Grammar\Lexeme('T_EQUAL', true),
        63 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        64 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', true),
        65 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', true),
        66 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', true),
        67 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        68 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        69 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        70 => new \Phplrt\Parser\Grammar\Lexeme('T_START_TIMESTAMP', true),
        71 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        72 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', true),
        73 => new \Phplrt\Parser\Grammar\Alternation([40, 'MetricValue', 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71]),
        74 => new \Phplrt\Parser\Grammar\Repetition(72, 0, INF),
        75 => new \Phplrt\Parser\Grammar\Concatenation([73, 74]),
        76 => new \Phplrt\Parser\Grammar\Lexeme('T_TEXT', true),
        77 => new \Phplrt\Parser\Grammar\Repetition(75, 0, INF),
        78 => new \Phplrt\Parser\Grammar\Optional(76),
        79 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        80 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        81 => new \Phplrt\Parser\Grammar\Repetition(79, 0, INF),
        82 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        83 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        84 => new \Phplrt\Parser\Grammar\Lexeme('T_TYPE', false),
        85 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        86 => new \Phplrt\Parser\Grammar\Alternation([40, 80]),
        87 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        88 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_TYPE', true),
        89 => new \Phplrt\Parser\Grammar\Optional(42),
        90 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        91 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        92 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        93 => new \Phplrt\Parser\Grammar\Concatenation([92, 'UnitUnit']),
        94 => new \Phplrt\Parser\Grammar\Repetition(90, 0, INF),
        95 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        96 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        97 => new \Phplrt\Parser\Grammar\Lexeme('T_UNIT', false),
        98 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        99 => new \Phplrt\Parser\Grammar\Alternation([40, 91]),
        100 => new \Phplrt\Parser\Grammar\Optional(93),
        101 => new \Phplrt\Parser\Grammar\Optional(42),
        102 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        103 => new \Phplrt\Parser\Grammar\Repetition(102, 0, INF),
        104 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        105 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        106 => new \Phplrt\Parser\Grammar\Lexeme('T_EOF', false),
        107 => new \Phplrt\Parser\Grammar\Optional(42),
        108 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        109 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', false),
        110 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', false),
        111 => new \Phplrt\Parser\Grammar\Concatenation([109, 'Labels', 110]),
        112 => new \Phplrt\Parser\Grammar\Optional(111),
        113 => new \Phplrt\Parser\Grammar\Concatenation([40, 112]),
        114 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        115 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', false),
        116 => new \Phplrt\Parser\Grammar\Repetition(114, 0, INF),
        117 => new \Phplrt\Parser\Grammar\Concatenation([115, 116, 'Labels']),
        118 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', false),
        119 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        120 => new \Phplrt\Parser\Grammar\Optional(117),
        121 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', false),
        122 => new \Phplrt\Parser\Grammar\Concatenation([118, 119, 120, 121]),
        123 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        124 => new \Phplrt\Parser\Grammar\Concatenation([123, 'MetricTimestamp']),
        125 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        126 => new \Phplrt\Parser\Grammar\Concatenation([125, 'MetricStartTimestamp']),
        127 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        128 => new \Phplrt\Parser\Grammar\Concatenation([127, 'Exemplars']),
        129 => new \Phplrt\Parser\Grammar\Repetition('Comment', 0, INF),
        130 => new \Phplrt\Parser\Grammar\Repetition(108, 0, INF),
        131 => new \Phplrt\Parser\Grammar\Alternation([113, 122]),
        132 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        133 => new \Phplrt\Parser\Grammar\Optional(124),
        134 => new \Phplrt\Parser\Grammar\Optional(126),
        135 => new \Phplrt\Parser\Grammar\Optional(128),
        136 => new \Phplrt\Parser\Grammar\Optional(42),
        137 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        138 => new \Phplrt\Parser\Grammar\Optional(137),
        139 => new \Phplrt\Parser\Grammar\Concatenation(['Exemplar', 138]),
        140 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        141 => new \Phplrt\Parser\Grammar\Concatenation([140, 'MetricTimestamp']),
        142 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        143 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        144 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', false),
        145 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', false),
        146 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        147 => new \Phplrt\Parser\Grammar\Optional(141),
        148 => new \Phplrt\Parser\Grammar\Alternation(['SummaryValue', 'HistogramValue', 'GaugeHistogramValue']),
        149 => new \Phplrt\Parser\Grammar\Lexeme('T_FLOAT', true),
        150 => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        151 => new \Phplrt\Parser\Grammar\Lexeme('T_INF', true),
        152 => new \Phplrt\Parser\Grammar\Lexeme('T_NAN', true),
        153 => new \Phplrt\Parser\Grammar\Concatenation([182, 183, 'Number']),
        154 => new \Phplrt\Parser\Grammar\Concatenation([186, 187, 'Number']),
        155 => new \Phplrt\Parser\Grammar\Concatenation([195, 196, 197, 198, 199]),
        156 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', true),
        157 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        158 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        159 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', true),
        160 => new \Phplrt\Parser\Grammar\Concatenation([202, 203, 204, 190, 205, 206]),
        161 => new \Phplrt\Parser\Grammar\Concatenation([243, 244, 'IntNumber', 245, 246, 247, 'Number', 248, 249, 250, 'Number', 251, 252, 253, 254]),
        162 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        163 => new \Phplrt\Parser\Grammar\Concatenation([162, 160]),
        164 => new \Phplrt\Parser\Grammar\Optional(163),
        165 => new \Phplrt\Parser\Grammar\Concatenation([161, 164]),
        166 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', true),
        167 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        168 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        169 => new \Phplrt\Parser\Grammar\Alternation([160, 165]),
        170 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', true),
        171 => new \Phplrt\Parser\Grammar\Concatenation([184, 185, 'Number']),
        172 => new \Phplrt\Parser\Grammar\Concatenation([188, 189, 'Number']),
        173 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        174 => new \Phplrt\Parser\Grammar\Concatenation([173, 160]),
        175 => new \Phplrt\Parser\Grammar\Optional(174),
        176 => new \Phplrt\Parser\Grammar\Concatenation([161, 175]),
        177 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', true),
        178 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        179 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        180 => new \Phplrt\Parser\Grammar\Alternation([160, 176]),
        181 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', true),
        182 => new \Phplrt\Parser\Grammar\Lexeme('T_COUNT', true),
        183 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        184 => new \Phplrt\Parser\Grammar\Lexeme('T_GCOUNT', true),
        185 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        186 => new \Phplrt\Parser\Grammar\Lexeme('T_SUM', true),
        187 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        188 => new \Phplrt\Parser\Grammar\Lexeme('T_GSUM', true),
        189 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        190 => new \Phplrt\Parser\Grammar\Concatenation(['Number', 255, 'Number']),
        191 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        192 => new \Phplrt\Parser\Grammar\Concatenation([191, 190]),
        193 => new \Phplrt\Parser\Grammar\Repetition(192, 0, INF),
        194 => new \Phplrt\Parser\Grammar\Concatenation([190, 193]),
        195 => new \Phplrt\Parser\Grammar\Lexeme('T_QUANTILE', true),
        196 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        197 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        198 => new \Phplrt\Parser\Grammar\Optional(194),
        199 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        200 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        201 => new \Phplrt\Parser\Grammar\Concatenation([200, 190]),
        202 => new \Phplrt\Parser\Grammar\Lexeme('T_BUCKET', true),
        203 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        204 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        205 => new \Phplrt\Parser\Grammar\Repetition(201, 0, INF),
        206 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        207 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        208 => new \Phplrt\Parser\Grammar\Concatenation([207, 190]),
        209 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        210 => new \Phplrt\Parser\Grammar\Lexeme('T_NEGATIVE_SPANS', true),
        211 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        212 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        213 => new \Phplrt\Parser\Grammar\Repetition(208, 0, INF),
        214 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        215 => new \Phplrt\Parser\Grammar\Concatenation([209, 210, 211, 212, 190, 213, 214]),
        216 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        217 => new \Phplrt\Parser\Grammar\Concatenation([216, 'Number']),
        218 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        219 => new \Phplrt\Parser\Grammar\Lexeme('T_NEGATIVE_BUCKETS', true),
        220 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        221 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        222 => new \Phplrt\Parser\Grammar\Repetition(217, 0, INF),
        223 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        224 => new \Phplrt\Parser\Grammar\Concatenation([218, 219, 220, 221, 'Number', 222, 223]),
        225 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        226 => new \Phplrt\Parser\Grammar\Concatenation([225, 190]),
        227 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        228 => new \Phplrt\Parser\Grammar\Lexeme('T_POSITIVE_SPANS', true),
        229 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        230 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        231 => new \Phplrt\Parser\Grammar\Repetition(226, 0, INF),
        232 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        233 => new \Phplrt\Parser\Grammar\Concatenation([227, 228, 229, 230, 190, 231, 232]),
        234 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        235 => new \Phplrt\Parser\Grammar\Concatenation([234, 'Number']),
        236 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        237 => new \Phplrt\Parser\Grammar\Lexeme('T_POSITIVE_BUCKETS', true),
        238 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        239 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        240 => new \Phplrt\Parser\Grammar\Repetition(235, 0, INF),
        241 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        242 => new \Phplrt\Parser\Grammar\Concatenation([236, 237, 238, 239, 'Number', 240, 241]),
        243 => new \Phplrt\Parser\Grammar\Lexeme('T_SCHEMA', true),
        244 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        245 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        246 => new \Phplrt\Parser\Grammar\Lexeme('T_ZERO_THRESHOLD', true),
        247 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        248 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        249 => new \Phplrt\Parser\Grammar\Lexeme('T_ZERO_COUNT', true),
        250 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        251 => new \Phplrt\Parser\Grammar\Optional(215),
        252 => new \Phplrt\Parser\Grammar\Optional(224),
        253 => new \Phplrt\Parser\Grammar\Optional(233),
        254 => new \Phplrt\Parser\Grammar\Optional(242),
        255 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        256 => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        257 => new \Phplrt\Parser\Grammar\Lexeme('T_FLOAT', true),
        258 => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        259 => new \Phplrt\Parser\Grammar\Lexeme('T_FLOAT', true),
        260 => new \Phplrt\Parser\Grammar\Lexeme('T_START_TIMESTAMP', false),
        261 => new \Phplrt\Parser\Grammar\Alternation([258, 259]),
        262 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        263 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', false),
        264 => new \Phplrt\Parser\Grammar\Repetition(262, 0, INF),
        265 => new \Phplrt\Parser\Grammar\Concatenation([263, 264]),
        266 => new \Phplrt\Parser\Grammar\Optional(265),
        267 => new \Phplrt\Parser\Grammar\Concatenation(['Label', 266]),
        268 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        269 => new \Phplrt\Parser\Grammar\Alternation([40, 268]),
        270 => new \Phplrt\Parser\Grammar\Lexeme('T_EQUAL', false),
        271 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        272 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        273 => new \Phplrt\Parser\Grammar\Repetition(272, 0, INF),
        274 => new \Phplrt\Parser\Grammar\Lexeme('T_EOL', false),
        275 => new \Phplrt\Parser\Grammar\Concatenation([273, 274]),
        'Comment' => new \Phplrt\Parser\Grammar\Concatenation([43, 44, 45]),
        'Document' => new \Phplrt\Parser\Grammar\Concatenation(['Schema']),
        'Eof' => new \Phplrt\Parser\Grammar\Concatenation([103, 104, 105, 106, 107]),
        'Exemplar' => new \Phplrt\Parser\Grammar\Concatenation([142, 143, 144, 'Labels', 145, 146, 'MetricValue', 147]),
        'Exemplars' => new \Phplrt\Parser\Grammar\Repetition(139, 0, INF),
        'GaugeHistogramValue' => new \Phplrt\Parser\Grammar\Concatenation([177, 171, 178, 172, 179, 180, 181]),
        'Help' => new \Phplrt\Parser\Grammar\Concatenation([50, 51, 52, 53, 54, 55, 56, 57]),
        'HelpDocstring' => new \Phplrt\Parser\Grammar\Concatenation([77, 78]),
        'HistogramValue' => new \Phplrt\Parser\Grammar\Concatenation([166, 153, 167, 154, 168, 169, 170]),
        'IntNumber' => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        'Label' => new \Phplrt\Parser\Grammar\Concatenation([269, 270, 271]),
        'Labels' => new \Phplrt\Parser\Grammar\Repetition(267, 0, INF),
        'Metric' => new \Phplrt\Parser\Grammar\Concatenation([129, 130, 131, 132, 'MetricValue', 133, 134, 135, 136]),
        'MetricData' => new \Phplrt\Parser\Grammar\Alternation([20, 23]),
        'MetricStartTimestamp' => new \Phplrt\Parser\Grammar\Concatenation([260, 261]),
        'MetricTimestamp' => new \Phplrt\Parser\Grammar\Alternation([256, 257]),
        'MetricValue' => new \Phplrt\Parser\Grammar\Alternation(['Number', 148]),
        'Number' => new \Phplrt\Parser\Grammar\Alternation([149, 150, 151, 152]),
        'Schema' => new \Phplrt\Parser\Grammar\Concatenation([0, 1]),
        'SummaryValue' => new \Phplrt\Parser\Grammar\Concatenation([156, 153, 157, 154, 158, 155, 159]),
        'Type' => new \Phplrt\Parser\Grammar\Concatenation([81, 82, 83, 84, 85, 86, 87, 88, 89]),
        'Unit' => new \Phplrt\Parser\Grammar\Concatenation([94, 95, 96, 97, 98, 99, 100, 101]),
        'UnitUnit' => new \Phplrt\Parser\Grammar\Concatenation([40]),
    ],
    'reducers' => [
        'Comment' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\CommentNode($children);
        },
        'Eof' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\EofNode($children);
        },
        'Exemplar' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\ExemplarNode($children);
        },
        'Exemplars' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\ExemplarsNode($children);
        },
        'GaugeHistogramValue' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\CompositeValue\GaugeHistogramValueNode($children);
        },
        'Help' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\HelpNode($children);
        },
        'HelpDocstring' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\HelpDocstringNode($children);
        },
        'HistogramValue' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\CompositeValue\HistogramValueNode($children);
        },
        'IntNumber' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\NumberNode($children);
        },
        'Label' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\LabelNode($children);
        },
        'Labels' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\LabelsNode($children);
        },
        'Metric' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricNode($children);
        },
        'MetricData' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricDataNode($children);
        },
        'MetricStartTimestamp' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricStartTimestampNode($children);
        },
        'MetricTimestamp' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricTimestampNode($children);
        },
        'MetricValue' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricValueNode($children);
        },
        'Number' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\NumberNode($children);
        },
        'Schema' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\SchemaNode($children);
        },
        'SummaryValue' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\CompositeValue\SummaryValueNode($children);
        },
        'Type' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\TypeNode($children);
        },
        'Unit' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\UnitNode($children);
        },
        'UnitUnit' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\UnitUnitNode($children);
        },
    ],
];