<?php

declare(strict_types=1);

/**
 * @var array{
 *     initial: array-key,
 *     tokens: array{
 *         default: array<non-empty-string, non-empty-string>,
 *         ...
 *     },
 *     skip: list<non-empty-string>,
 *     grammar: array<array-key, \Phplrt\Parser\Grammar\RuleInterface>,
 *     reducers: array<array-key, callable(\Phplrt\Parser\Context, mixed):mixed>,
 *     transitions?: array<array-key, mixed>
 * }
 */
return [
    'initial' => 'Document',
    'tokens' => [
        'default' => [
            'T_WHITESPACE' => '[\\x20\\t]+',
            'T_HELP' => '\\bHELP\\b',
            'T_TYPE' => '\\bTYPE\\b',
            'T_UNIT' => '\\bUNIT\\b',
            'T_EOF' => '\\bEOF\\b',
            'T_COMMENT' => '^\\#(?![\\x20\\t]+(?:HELP|TYPE|UNIT|EOF)\\b)[\\x20\\t]*([^\\n\\\\]|\\\\[n"\\\\]|\\\\)*$',
            'T_FLOAT' => '[+-]?[0-9]*\\.[0-9]+([eE][+-]?[0-9]+)?|[+-]?[0-9]+[eE][+-]?[0-9]+\\b',
            'T_INF' => '[+-]?(?i)inf(inity)?\\b',
            'T_INT' => '[+-]?[0-9]+',
            'T_NAN' => '\\b(?i)nan\\b(?!:)',
            'T_EQUAL' => '=',
            'T_COLON' => '(?<=[a-zA-Z0-9_]):',
            'T_HASH' => '#',
            'T_LBRACE' => '{',
            'T_RBRACE' => '}',
            'T_LBRACKET' => '\\[',
            'T_RBRACKET' => '\\]',
            'T_COMMA' => ',',
            'T_EOR' => '\\r',
            'T_EOL' => '\\n',
            'T_START_TIMESTAMP' => '\\bst@',
            'T_METRIC_TYPE' => '\\b(summary|counter|gaugehistogram|gauge|histogram|stateset|info|unknown|untyped)\\b(?!:)',
            'T_COUNT' => '(?<=[{,])\\bcount\\b',
            'T_GCOUNT' => '(?<=[{,])\\bgcount\\b',
            'T_SUM' => '(?<=[{,])\\bsum\\b',
            'T_GSUM' => '(?<=[{,])\\bgsum\\b',
            'T_QUANTILE' => '(?<=[{,])\\bquantile\\b',
            'T_SCHEMA' => '(?<=[{,])\\bschema\\b',
            'T_ZERO_THRESHOLD' => '(?<=[{,])\\bzero_threshold\\b',
            'T_ZERO_COUNT' => '(?<=[{,])\\bzero_count\\b',
            'T_NEGATIVE_SPANS' => '(?<=[{,])\\bnegative_spans\\b',
            'T_NEGATIVE_BUCKETS' => '(?<=[{,])\\bnegative_buckets\\b',
            'T_POSITIVE_SPANS' => '(?<=[{,])\\bpositive_spans\\b',
            'T_POSITIVE_BUCKETS' => '(?<=[{,])\\bpositive_buckets\\b',
            'T_BUCKET' => '(?<=[{,])\\bbucket\\b',
            'T_METRIC_NAME' => '[a-zA-Z_:][a-zA-Z0-9_:]*',
            'T_QUOTED_STRING' => '\\"([^\\n"\\\\]|\\\\[n"\\\\])*\\"',
            'T_TEXT' => '([^\\n\\\\]|\\\\[n"\\\\]|\\\\)+',
        ],
    ],
    'skip' => [],
    'transitions' => [],
    'grammar' => [
        0 => new \Phplrt\Parser\Grammar\Repetition(278, 1, INF),
        1 => new \Phplrt\Parser\Grammar\Optional(0),
        2 => new \Phplrt\Parser\Grammar\Repetition('MetricData', 0, INF),
        3 => new \Phplrt\Parser\Grammar\Optional('Eof'),
        4 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        5 => new \Phplrt\Parser\Grammar\Concatenation(['Help', 'Type', 4]),
        6 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        7 => new \Phplrt\Parser\Grammar\Optional('Type'),
        8 => new \Phplrt\Parser\Grammar\Concatenation(['Help', 6, 7]),
        9 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        10 => new \Phplrt\Parser\Grammar\Concatenation(['Type', 'Help', 9]),
        11 => new \Phplrt\Parser\Grammar\Optional('Unit'),
        12 => new \Phplrt\Parser\Grammar\Optional('Help'),
        13 => new \Phplrt\Parser\Grammar\Concatenation(['Type', 11, 12]),
        14 => new \Phplrt\Parser\Grammar\Optional('Help'),
        15 => new \Phplrt\Parser\Grammar\Concatenation(['Unit', 'Type', 14]),
        16 => new \Phplrt\Parser\Grammar\Optional('Help'),
        17 => new \Phplrt\Parser\Grammar\Optional('Type'),
        18 => new \Phplrt\Parser\Grammar\Concatenation(['Unit', 16, 17]),
        19 => new \Phplrt\Parser\Grammar\Repetition('Comment', 0, INF),
        20 => new \Phplrt\Parser\Grammar\Alternation([5, 8, 10, 13, 15, 18]),
        21 => new \Phplrt\Parser\Grammar\Repetition('Metric', 0, INF),
        22 => new \Phplrt\Parser\Grammar\Concatenation([19, 20, 21]),
        23 => new \Phplrt\Parser\Grammar\Repetition('Comment', 0, INF),
        24 => new \Phplrt\Parser\Grammar\Concatenation([23, 'Metric']),
        25 => new \Phplrt\Parser\Grammar\Repetition('Comment', 1, INF),
        26 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_NAME', true),
        27 => new \Phplrt\Parser\Grammar\Lexeme('T_NAN', true),
        28 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_TYPE', true),
        29 => new \Phplrt\Parser\Grammar\Lexeme('T_COUNT', true),
        30 => new \Phplrt\Parser\Grammar\Lexeme('T_GCOUNT', true),
        31 => new \Phplrt\Parser\Grammar\Lexeme('T_SUM', true),
        32 => new \Phplrt\Parser\Grammar\Lexeme('T_GSUM', true),
        33 => new \Phplrt\Parser\Grammar\Lexeme('T_QUANTILE', true),
        34 => new \Phplrt\Parser\Grammar\Lexeme('T_SCHEMA', true),
        35 => new \Phplrt\Parser\Grammar\Lexeme('T_ZERO_THRESHOLD', true),
        36 => new \Phplrt\Parser\Grammar\Lexeme('T_ZERO_COUNT', true),
        37 => new \Phplrt\Parser\Grammar\Lexeme('T_NEGATIVE_SPANS', true),
        38 => new \Phplrt\Parser\Grammar\Lexeme('T_NEGATIVE_BUCKETS', true),
        39 => new \Phplrt\Parser\Grammar\Lexeme('T_POSITIVE_SPANS', true),
        40 => new \Phplrt\Parser\Grammar\Lexeme('T_POSITIVE_BUCKETS', true),
        41 => new \Phplrt\Parser\Grammar\Lexeme('T_BUCKET', true),
        42 => new \Phplrt\Parser\Grammar\Alternation([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41]),
        43 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        44 => new \Phplrt\Parser\Grammar\Repetition(43, 0, INF),
        45 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMENT', true),
        46 => new \Phplrt\Parser\Grammar\Optional(0),
        47 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        48 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        49 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        50 => new \Phplrt\Parser\Grammar\Concatenation([49, 'HelpDocstring']),
        51 => new \Phplrt\Parser\Grammar\Repetition(47, 0, INF),
        52 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        53 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        54 => new \Phplrt\Parser\Grammar\Lexeme('T_HELP', false),
        55 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        56 => new \Phplrt\Parser\Grammar\Alternation([42, 48]),
        57 => new \Phplrt\Parser\Grammar\Optional(50),
        58 => new \Phplrt\Parser\Grammar\Optional(0),
        59 => new \Phplrt\Parser\Grammar\Lexeme('T_HELP', true),
        60 => new \Phplrt\Parser\Grammar\Lexeme('T_TYPE', true),
        61 => new \Phplrt\Parser\Grammar\Lexeme('T_UNIT', true),
        62 => new \Phplrt\Parser\Grammar\Lexeme('T_EOF', true),
        63 => new \Phplrt\Parser\Grammar\Lexeme('T_EQUAL', true),
        64 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        65 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', true),
        66 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', true),
        67 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', true),
        68 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        69 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        70 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        71 => new \Phplrt\Parser\Grammar\Lexeme('T_START_TIMESTAMP', true),
        72 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        73 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', true),
        74 => new \Phplrt\Parser\Grammar\Alternation([42, 'MetricValue', 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]),
        75 => new \Phplrt\Parser\Grammar\Repetition(73, 0, INF),
        76 => new \Phplrt\Parser\Grammar\Concatenation([74, 75]),
        77 => new \Phplrt\Parser\Grammar\Lexeme('T_TEXT', true),
        78 => new \Phplrt\Parser\Grammar\Repetition(76, 0, INF),
        79 => new \Phplrt\Parser\Grammar\Optional(77),
        80 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        81 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        82 => new \Phplrt\Parser\Grammar\Repetition(80, 0, INF),
        83 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        84 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        85 => new \Phplrt\Parser\Grammar\Lexeme('T_TYPE', false),
        86 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        87 => new \Phplrt\Parser\Grammar\Alternation([42, 81]),
        88 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        89 => new \Phplrt\Parser\Grammar\Lexeme('T_METRIC_TYPE', true),
        90 => new \Phplrt\Parser\Grammar\Optional(0),
        91 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        92 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        93 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        94 => new \Phplrt\Parser\Grammar\Concatenation([93, 'UnitUnit']),
        95 => new \Phplrt\Parser\Grammar\Repetition(91, 0, INF),
        96 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        97 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        98 => new \Phplrt\Parser\Grammar\Lexeme('T_UNIT', false),
        99 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        100 => new \Phplrt\Parser\Grammar\Alternation([42, 92]),
        101 => new \Phplrt\Parser\Grammar\Optional(94),
        102 => new \Phplrt\Parser\Grammar\Optional(0),
        103 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        104 => new \Phplrt\Parser\Grammar\Repetition(103, 0, INF),
        105 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        106 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        107 => new \Phplrt\Parser\Grammar\Lexeme('T_EOF', false),
        108 => new \Phplrt\Parser\Grammar\Optional(0),
        109 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        110 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', false),
        111 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', false),
        112 => new \Phplrt\Parser\Grammar\Concatenation([110, 'Labels', 111]),
        113 => new \Phplrt\Parser\Grammar\Optional(112),
        114 => new \Phplrt\Parser\Grammar\Concatenation([42, 113]),
        115 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        116 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', false),
        117 => new \Phplrt\Parser\Grammar\Repetition(115, 0, INF),
        118 => new \Phplrt\Parser\Grammar\Concatenation([116, 117, 'Labels']),
        119 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', false),
        120 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        121 => new \Phplrt\Parser\Grammar\Optional(118),
        122 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', false),
        123 => new \Phplrt\Parser\Grammar\Concatenation([119, 120, 121, 122]),
        124 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        125 => new \Phplrt\Parser\Grammar\Concatenation([124, 'MetricTimestamp']),
        126 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        127 => new \Phplrt\Parser\Grammar\Concatenation([126, 'MetricStartTimestamp']),
        128 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        129 => new \Phplrt\Parser\Grammar\Concatenation([128, 'Exemplars']),
        130 => new \Phplrt\Parser\Grammar\Repetition('Comment', 0, INF),
        131 => new \Phplrt\Parser\Grammar\Repetition(109, 0, INF),
        132 => new \Phplrt\Parser\Grammar\Alternation([114, 123]),
        133 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        134 => new \Phplrt\Parser\Grammar\Optional(125),
        135 => new \Phplrt\Parser\Grammar\Optional(127),
        136 => new \Phplrt\Parser\Grammar\Optional(129),
        137 => new \Phplrt\Parser\Grammar\Optional(0),
        138 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        139 => new \Phplrt\Parser\Grammar\Optional(138),
        140 => new \Phplrt\Parser\Grammar\Concatenation(['Exemplar', 139]),
        141 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        142 => new \Phplrt\Parser\Grammar\Concatenation([141, 'MetricTimestamp']),
        143 => new \Phplrt\Parser\Grammar\Lexeme('T_HASH', false),
        144 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        145 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', false),
        146 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', false),
        147 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        148 => new \Phplrt\Parser\Grammar\Optional(142),
        149 => new \Phplrt\Parser\Grammar\Alternation(['SummaryValue', 'HistogramValue', 'GaugeHistogramValue']),
        150 => new \Phplrt\Parser\Grammar\Lexeme('T_FLOAT', true),
        151 => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        152 => new \Phplrt\Parser\Grammar\Lexeme('T_INF', true),
        153 => new \Phplrt\Parser\Grammar\Lexeme('T_NAN', true),
        154 => new \Phplrt\Parser\Grammar\Concatenation([183, 184, 'Number']),
        155 => new \Phplrt\Parser\Grammar\Concatenation([187, 188, 'Number']),
        156 => new \Phplrt\Parser\Grammar\Concatenation([196, 197, 198, 199, 200]),
        157 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', true),
        158 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        159 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        160 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', true),
        161 => new \Phplrt\Parser\Grammar\Concatenation([203, 204, 205, 191, 206, 207]),
        162 => new \Phplrt\Parser\Grammar\Concatenation([244, 245, 'IntNumber', 246, 247, 248, 'Number', 249, 250, 251, 'Number', 252, 253, 254, 255]),
        163 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        164 => new \Phplrt\Parser\Grammar\Concatenation([163, 161]),
        165 => new \Phplrt\Parser\Grammar\Optional(164),
        166 => new \Phplrt\Parser\Grammar\Concatenation([162, 165]),
        167 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', true),
        168 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        169 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        170 => new \Phplrt\Parser\Grammar\Alternation([161, 166]),
        171 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', true),
        172 => new \Phplrt\Parser\Grammar\Concatenation([185, 186, 'Number']),
        173 => new \Phplrt\Parser\Grammar\Concatenation([189, 190, 'Number']),
        174 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        175 => new \Phplrt\Parser\Grammar\Concatenation([174, 161]),
        176 => new \Phplrt\Parser\Grammar\Optional(175),
        177 => new \Phplrt\Parser\Grammar\Concatenation([162, 176]),
        178 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACE', true),
        179 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        180 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        181 => new \Phplrt\Parser\Grammar\Alternation([161, 177]),
        182 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACE', true),
        183 => new \Phplrt\Parser\Grammar\Lexeme('T_COUNT', true),
        184 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        185 => new \Phplrt\Parser\Grammar\Lexeme('T_GCOUNT', true),
        186 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        187 => new \Phplrt\Parser\Grammar\Lexeme('T_SUM', true),
        188 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        189 => new \Phplrt\Parser\Grammar\Lexeme('T_GSUM', true),
        190 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        191 => new \Phplrt\Parser\Grammar\Concatenation(['Number', 256, 'Number']),
        192 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        193 => new \Phplrt\Parser\Grammar\Concatenation([192, 191]),
        194 => new \Phplrt\Parser\Grammar\Repetition(193, 0, INF),
        195 => new \Phplrt\Parser\Grammar\Concatenation([191, 194]),
        196 => new \Phplrt\Parser\Grammar\Lexeme('T_QUANTILE', true),
        197 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        198 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        199 => new \Phplrt\Parser\Grammar\Optional(195),
        200 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        201 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        202 => new \Phplrt\Parser\Grammar\Concatenation([201, 191]),
        203 => new \Phplrt\Parser\Grammar\Lexeme('T_BUCKET', true),
        204 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        205 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        206 => new \Phplrt\Parser\Grammar\Repetition(202, 0, INF),
        207 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        208 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        209 => new \Phplrt\Parser\Grammar\Concatenation([208, 191]),
        210 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        211 => new \Phplrt\Parser\Grammar\Lexeme('T_NEGATIVE_SPANS', true),
        212 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        213 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        214 => new \Phplrt\Parser\Grammar\Repetition(209, 0, INF),
        215 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        216 => new \Phplrt\Parser\Grammar\Concatenation([210, 211, 212, 213, 191, 214, 215]),
        217 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        218 => new \Phplrt\Parser\Grammar\Concatenation([217, 'Number']),
        219 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        220 => new \Phplrt\Parser\Grammar\Lexeme('T_NEGATIVE_BUCKETS', true),
        221 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        222 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        223 => new \Phplrt\Parser\Grammar\Repetition(218, 0, INF),
        224 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        225 => new \Phplrt\Parser\Grammar\Concatenation([219, 220, 221, 222, 'Number', 223, 224]),
        226 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        227 => new \Phplrt\Parser\Grammar\Concatenation([226, 191]),
        228 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        229 => new \Phplrt\Parser\Grammar\Lexeme('T_POSITIVE_SPANS', true),
        230 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        231 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        232 => new \Phplrt\Parser\Grammar\Repetition(227, 0, INF),
        233 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        234 => new \Phplrt\Parser\Grammar\Concatenation([228, 229, 230, 231, 191, 232, 233]),
        235 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        236 => new \Phplrt\Parser\Grammar\Concatenation([235, 'Number']),
        237 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        238 => new \Phplrt\Parser\Grammar\Lexeme('T_POSITIVE_BUCKETS', true),
        239 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        240 => new \Phplrt\Parser\Grammar\Lexeme('T_LBRACKET', true),
        241 => new \Phplrt\Parser\Grammar\Repetition(236, 0, INF),
        242 => new \Phplrt\Parser\Grammar\Lexeme('T_RBRACKET', true),
        243 => new \Phplrt\Parser\Grammar\Concatenation([237, 238, 239, 240, 'Number', 241, 242]),
        244 => new \Phplrt\Parser\Grammar\Lexeme('T_SCHEMA', true),
        245 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        246 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        247 => new \Phplrt\Parser\Grammar\Lexeme('T_ZERO_THRESHOLD', true),
        248 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        249 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', true),
        250 => new \Phplrt\Parser\Grammar\Lexeme('T_ZERO_COUNT', true),
        251 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        252 => new \Phplrt\Parser\Grammar\Optional(216),
        253 => new \Phplrt\Parser\Grammar\Optional(225),
        254 => new \Phplrt\Parser\Grammar\Optional(234),
        255 => new \Phplrt\Parser\Grammar\Optional(243),
        256 => new \Phplrt\Parser\Grammar\Lexeme('T_COLON', true),
        257 => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        258 => new \Phplrt\Parser\Grammar\Lexeme('T_FLOAT', true),
        259 => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        260 => new \Phplrt\Parser\Grammar\Lexeme('T_FLOAT', true),
        261 => new \Phplrt\Parser\Grammar\Lexeme('T_START_TIMESTAMP', false),
        262 => new \Phplrt\Parser\Grammar\Alternation([259, 260]),
        263 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        264 => new \Phplrt\Parser\Grammar\Lexeme('T_COMMA', false),
        265 => new \Phplrt\Parser\Grammar\Repetition(263, 0, INF),
        266 => new \Phplrt\Parser\Grammar\Concatenation([264, 265]),
        267 => new \Phplrt\Parser\Grammar\Optional(266),
        268 => new \Phplrt\Parser\Grammar\Concatenation(['Label', 267]),
        269 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        270 => new \Phplrt\Parser\Grammar\Alternation([42, 269]),
        271 => new \Phplrt\Parser\Grammar\Lexeme('T_EQUAL', false),
        272 => new \Phplrt\Parser\Grammar\Lexeme('T_QUOTED_STRING', true),
        273 => new \Phplrt\Parser\Grammar\Lexeme('T_WHITESPACE', false),
        274 => new \Phplrt\Parser\Grammar\Lexeme('T_EOR', false),
        275 => new \Phplrt\Parser\Grammar\Repetition(273, 0, INF),
        276 => new \Phplrt\Parser\Grammar\Optional(274),
        277 => new \Phplrt\Parser\Grammar\Lexeme('T_EOL', false),
        278 => new \Phplrt\Parser\Grammar\Concatenation([275, 276, 277]),
        'Comment' => new \Phplrt\Parser\Grammar\Concatenation([44, 45, 46]),
        'Document' => new \Phplrt\Parser\Grammar\Concatenation(['Schema']),
        'Eof' => new \Phplrt\Parser\Grammar\Concatenation([104, 105, 106, 107, 108]),
        'Exemplar' => new \Phplrt\Parser\Grammar\Concatenation([143, 144, 145, 'Labels', 146, 147, 'MetricValue', 148]),
        'Exemplars' => new \Phplrt\Parser\Grammar\Repetition(140, 0, INF),
        'GaugeHistogramValue' => new \Phplrt\Parser\Grammar\Concatenation([178, 172, 179, 173, 180, 181, 182]),
        'Help' => new \Phplrt\Parser\Grammar\Concatenation([51, 52, 53, 54, 55, 56, 57, 58]),
        'HelpDocstring' => new \Phplrt\Parser\Grammar\Concatenation([78, 79]),
        'HistogramValue' => new \Phplrt\Parser\Grammar\Concatenation([167, 154, 168, 155, 169, 170, 171]),
        'IntNumber' => new \Phplrt\Parser\Grammar\Lexeme('T_INT', true),
        'Label' => new \Phplrt\Parser\Grammar\Concatenation([270, 271, 272]),
        'Labels' => new \Phplrt\Parser\Grammar\Repetition(268, 0, INF),
        'Metric' => new \Phplrt\Parser\Grammar\Concatenation([130, 131, 132, 133, 'MetricValue', 134, 135, 136, 137]),
        'MetricData' => new \Phplrt\Parser\Grammar\Alternation([22, 24, 25]),
        'MetricStartTimestamp' => new \Phplrt\Parser\Grammar\Concatenation([261, 262]),
        'MetricTimestamp' => new \Phplrt\Parser\Grammar\Alternation([257, 258]),
        'MetricValue' => new \Phplrt\Parser\Grammar\Alternation(['Number', 149]),
        'Number' => new \Phplrt\Parser\Grammar\Alternation([150, 151, 152, 153]),
        'Schema' => new \Phplrt\Parser\Grammar\Concatenation([1, 2, 3]),
        'SummaryValue' => new \Phplrt\Parser\Grammar\Concatenation([157, 154, 158, 155, 159, 156, 160]),
        'Type' => new \Phplrt\Parser\Grammar\Concatenation([82, 83, 84, 85, 86, 87, 88, 89, 90]),
        'Unit' => new \Phplrt\Parser\Grammar\Concatenation([95, 96, 97, 98, 99, 100, 101, 102]),
        'UnitUnit' => new \Phplrt\Parser\Grammar\Concatenation([42]),
    ],
    'reducers' => [
        'Comment' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\CommentNode($children);
        },
        'Eof' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\EofNode($children);
        },
        'Exemplar' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\ExemplarNode($children);
        },
        'Exemplars' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\ExemplarsNode($children);
        },
        'GaugeHistogramValue' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\CompositeValue\GaugeHistogramValueNode($children);
        },
        'Help' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\HelpNode($children);
        },
        'HelpDocstring' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\HelpDocstringNode($children);
        },
        'HistogramValue' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\CompositeValue\HistogramValueNode($children);
        },
        'IntNumber' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\NumberNode($children);
        },
        'Label' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\LabelNode($children);
        },
        'Labels' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\LabelsNode($children);
        },
        'Metric' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricNode($children);
        },
        'MetricData' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricDataNode($children);
        },
        'MetricStartTimestamp' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricStartTimestampNode($children);
        },
        'MetricTimestamp' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricTimestampNode($children);
        },
        'MetricValue' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\MetricValueNode($children);
        },
        'Number' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\NumberNode($children);
        },
        'Schema' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\SchemaNode($children);
        },
        'SummaryValue' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\CompositeValue\SummaryValueNode($children);
        },
        'Type' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\TypeNode($children);
        },
        'Unit' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\UnitNode($children);
        },
        'UnitUnit' => static function (\Phplrt\Parser\Context $ctx, $children) {
            return new \Butschster\Prometheus\Ast\UnitUnitNode($children);
        },
    ],
];